---
driver:
  name: docker
  hostname: opencontrail
  use_sudo: false

provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_version: latest
  require_chef: false
  log_level: error
  formula: opencontrail
  grains:
    noservices: True
  dependencies:
    - name: linux
      repo: git
      source: https://github.com/salt-formulas/salt-formula-linux
  state_top:
    base:
      "*":
        - linux
        - opencontrail
  pillars:
    top.sls:
      base:
        "*":
          - linux_repo_openstack
          - linux_repo_opencontrail
          - linux_repo_cassandra
          - linux
          - opencontrail
          - opencontrail_juniper
    linux.sls:
      linux:
        system:
          enabled: true
          name: opencontrail
    opencontrail_juniper.sls: {}
  pillars-from-files:
    linux_repo_cassandra.sls: tests/pillar/repo_cassandra.sls
    linux_repo_opencontrail.sls: tests/pillar/repo_opencontrail_<%= ENV['OC_REPO'] || 'oc311' %>.sls
    linux_repo_openstack.sls: tests/pillar/repo_openstack.sls

verifier:
  name: inspec
  sudo: true

platforms:
  - name: <%=ENV['PLATFORM'] ||  'saltstack-ubuntu-xenial-salt-stable' %>
    driver_config:
      image: <%=ENV['PLATFORM'] || 'epcim/salt:saltstack-ubuntu-xenial-salt-stable'%>
      platform: ubuntu

suites:

  - name: single3
    provisioner:
      pillars-from-files:
        opencontrail.sls: tests/pillar/single3.sls
  - name: single40
    provisioner:
      grains:
        init: 'systemd'
      pillars-from-files:
        opencontrail.sls: tests/pillar/single40.sls
  - name: analytics3
    provisioner:
      pillars-from-files:
        opencontrail.sls: tests/pillar/analytics3.sls
  - name: analytics40
    provisioner:
      grains:
        init: 'systemd'
      pillars-from-files:
        opencontrail.sls: tests/pillar/analytics40.sls
  - name: control3
    provisioner:
      pillars-from-files:
        opencontrail.sls: tests/pillar/control3.sls
  - name: control40
    provisioner:
      grains:
        init: 'systemd'
      pillars-from-files:
        opencontrail.sls: tests/pillar/control40.sls
  - name: cluster3
    provisioner:
      pillars-from-files:
        opencontrail.sls: tests/pillar/cluster3.sls
  - name: cluster40
    provisioner:
      grains:
        init: 'systemd'
      pillars-from-files:
        opencontrail.sls: tests/pillar/cluster40.sls
  # - name: tor3
  #   provisioner:
  #     pillars-from-files:
  #       opencontrail.sls: tests/pillar/tor3.sls
  # - name: tor40
  #   provisioner:
  #     pillars-from-files:
  #       opencontrail.sls: tests/pillar/tor40.sls
  - name: vrouter3
    provisioner:
      pillars-from-files:
        opencontrail.sls: tests/pillar/vrouter3.sls
  - name: vrouter40
    provisioner:
      grains:
        init: 'systemd'
      pillars-from-files:
        opencontrail.sls: tests/pillar/vrouter40.sls

# vim: ft=yaml sw=2 ts=2 sts=2 tw=125
